import { useState } from "react";
import "./FinancingSection.css";

const WHATSAPP = "5492235896986";
const inicial = { dni:"", nombreCompleto:"", email:"", telefono:"", localidad:"", sucursal:"", anticipo:"", moneda:"ARS", moto:"" };

function FinancingSection({ motos=[] }) {
  const [formulario,setFormulario]=useState(inicial); const [enviado,setEnviado]=useState(false);
  const cambiar=({target})=>{let value=target.value;if(target.name==="dni")value=value.replace(/\D/g,"").slice(0,10);if(["nombreCompleto","localidad"].includes(target.name))value=value.replace(/[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]/g,"");setFormulario((x)=>({...x,[target.name]:value}));setEnviado(false);};
  const enviar=(event)=>{event.preventDefault();if(!event.currentTarget.checkValidity()){event.currentTarget.reportValidity();return;}const moto=motos.find((x)=>x._id===formulario.moto);const nombreMoto=moto?`${moto.marca?.nombre||""} ${moto.nombre}`.trim():"Sin modelo específico";const mensaje=`Hola, quiero solicitar información sobre financiación.\n\nDatos personales:\n- DNI: ${formulario.dni}\n- Nombre: ${formulario.nombreCompleto}\n- Email: ${formulario.email}\n- Teléfono: ${formulario.telefono}\n- Localidad: ${formulario.localidad}\n\nSolicitud:\n- Sucursal: ${formulario.sucursal}\n- Moto: ${nombreMoto}\n- Anticipo: ${formulario.moneda} ${formulario.anticipo||"0"}\n\nQuedo a la espera de un asesor.`;setEnviado(true);window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(mensaje)}`,"_blank","noopener,noreferrer");};

  return <section id="financiacion" className="financing"><div className="financing__container"><div className="financing__heading"><span className="financing__tag"><i className="bi bi-credit-card-2-front"/>Financiación</span><h2>Dejanos tus datos.<span> Te respondemos en el día.</span></h2><p>Completá el formulario. Al enviarlo se abrirá WhatsApp con tu solicitud preparada; revisá el mensaje y presioná Enviar para contactar al asesor.</p></div>
    <div className="financing__layout"><form className="financing__form" onSubmit={enviar}><div className="financing__form-grid">
      <Campo label="DNI" requerido><input name="dni" type="text" inputMode="numeric" pattern="[0-9]{7,10}" title="Ingresá entre 7 y 10 números" placeholder="Ej: 12345678" value={formulario.dni} onChange={cambiar} required/></Campo>
      <Campo label="Nombre y apellido" requerido><input name="nombreCompleto" type="text" pattern="[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]{3,80}" title="Usá únicamente letras y espacios" placeholder="Tu nombre completo" value={formulario.nombreCompleto} onChange={cambiar} required/></Campo>
      <Campo label="Email" requerido><input name="email" type="email" placeholder="nombre@email.com" value={formulario.email} onChange={cambiar} required/></Campo>
      <Campo label="Número de teléfono" requerido><input name="telefono" type="tel" inputMode="tel" pattern="\+?[0-9 ()-]{8,20}" title="Ingresá un teléfono válido de 8 a 20 caracteres" placeholder="+54 9 223..." value={formulario.telefono} onChange={cambiar} required/></Campo>
      <Campo label="Localidad" requerido><input name="localidad" type="text" pattern="[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]{2,80}" title="Usá únicamente letras y espacios" placeholder="Ej: Mar del Plata" value={formulario.localidad} onChange={cambiar} required/></Campo>
      <Campo label="Sucursal" requerido><select name="sucursal" value={formulario.sucursal} onChange={cambiar} required><option value="">Seleccioná una sucursal</option><option value="Mar del Plata">Mar del Plata</option><option value="Otra sucursal">Otra sucursal</option></select></Campo>
      <Campo label="Moto de interés" requerido><select name="moto" value={formulario.moto} onChange={cambiar} required><option value="">Seleccioná una moto</option>{motos.map((moto)=><option key={moto._id} value={moto._id}>{moto.marca?.nombre||""} {moto.nombre}</option>)}</select></Campo>
      <div className="financing__field financing__field--advance"><label htmlFor="anticipo">¿Contás con anticipo?</label><div className="financing__advance"><input id="anticipo" name="anticipo" type="number" inputMode="numeric" min="0" step="1" placeholder="Ej: 1000000" value={formulario.anticipo} onChange={cambiar}/><select name="moneda" aria-label="Moneda" value={formulario.moneda} onChange={cambiar}><option value="ARS">ARS</option><option value="USD">USD</option></select></div></div>
    </div><div className="financing__form-footer"><button type="submit" className="financing__submit">Preparar solicitud en WhatsApp <i className="bi bi-whatsapp"/></button><p><i className="bi bi-shield-check"/>No se enviará automáticamente: podrás revisar el mensaje antes de enviarlo.</p></div>{enviado&&<div className="financing__success"><i className="bi bi-check-circle-fill"/><div><strong>Solicitud preparada</strong><span>WhatsApp se abrió con los datos. Falta presionar Enviar dentro de WhatsApp.</span></div></div>}</form>
      <aside className="financing__information"><Info icon="bi-person-vcard" title="Consultá solamente con tu DNI">Un asesor revisará tu solicitud y te explicará las alternativas disponibles.</Info><Info icon="bi-clock-history" title="Te contactamos en el día">Analizamos tus datos y buscamos una opción adaptada a tu presupuesto.</Info><article className="financing__info-card financing__info-card--dark"><span className="financing__info-label">Atención comercial</span><h3>¿Preferís hablar directamente?</h3><p>Escribinos por WhatsApp y consultá con un asesor.</p><a href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/>Hablar por WhatsApp</a></article></aside>
    </div></div></section>;
}

function Campo({label,requerido,children}){return <div className="financing__field"><label>{label} {requerido&&<span>*</span>}</label>{children}</div>}
function Info({icon,title,children}){return <article className="financing__info-card"><span className="financing__info-label">Información</span><div className="financing__info-icon"><i className={`bi ${icon}`}/></div><h3>{title}</h3><p>{children}</p></article>}
export default FinancingSection;
